packages:
  - '.'
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - '@google/genai'
  - protobufjs
overrides:
  vite: 6.3.5
supportedArchitectures:
  os:
    - win32
    - linux
  cpu:
    - x64
    - arm64
  libc:
    - glibc
